version: '3'
services:
  # https://github.com/plexinc/pms-docker
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
    volumes:
      - ${BASE_DIR}/config/plex-config:/config
      - ${BASE_DIR}/data/transcode:/transcode
      - ${BASE_DIR}/data/media:/data
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DIR}/config/sabnzbd-config:/config
      - ${BASE_DIR}/data/usenet:/data/usenet
    ports:
      - "8080:8080"
    # network_mode: host
    restart: unless-stopped
  
  # https://docs.linuxserver.io/images/docker-qbittorrent/
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8081
    volumes:
      - ${BASE_DIR}/config/qbittorrent-config:/config
      - ${BASE_DIR}/data/torrents:/data/torrents
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DIR}/config/sonarr-config:/config
      - ${BASE_DIR}/data:/data
    ports:
      - "8989:8989"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DIR}/config/radarr-config:/config
      - ${BASE_DIR}/data:/data
    ports:
      - "7878:7878"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DIR}/config/lidarr-config:/config
      - ${BASE_DIR}/data:/data
    ports:
      - "8686:8686"
    # network_mode: host
    restart: unless-stopped
  
  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DIR}/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_DIR}/config/overseerr-config:/app/config
    ports:
      - "5055:5055"
    # network_mode: host
    restart: unless-stopped
