version: "3.4"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${BASE_CONFIG_DIR}/plex-config:/config
      - ${BASE_MEDIA_DIR}/transcode:/transcode
      - ${BASE_MEDIA_DIR}/media:/data
    ports:
      - "32400:32400" # Main web port
      - "32410:32410" # current GDM network discovery
      - "32412:32412" # current GDM network discovery
      - "32413:32413" # current GDM network discovery
      - "32414:32414" # current GDM network discovery
    restart: unless-stopped
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [gpu]

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/sabnzbd-config:/config
      - ${BASE_MEDIA_DIR}/usenet:/data/usenet
    ports:
      - "8080:8080"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-qbittorrent/
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8081
    volumes:
      - ${BASE_CONFIG_DIR}/qbittorrent-config:/config
      - ${BASE_MEDIA_DIR}/torrents:/data/torrents
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/sonarr-config:/config
      - ${BASE_MEDIA_DIR}:/data
    ports:
      - "8989:8989"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/radarr-config:/config
      - ${BASE_MEDIA_DIR}:/data
    ports:
      - "7878:7878"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/lidarr-config:/config
      - ${BASE_MEDIA_DIR}:/data
    ports:
      - "8686:8686"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/bazarr-config:/config
      - ${BASE_MEDIA_DIR}:/data
    ports:
      - "6767:6767"
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/prowlarr-config:/config
    ports:
      - "9696:9696"
    # network_mode: host
    restart: unless-stopped

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${BASE_CONFIG_DIR}/overseerr-config:/app/config
    ports:
      - "5055:5055"
    # network_mode: host
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/London
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${BASE_CONFIG_DIR}/tdarr/server:/app/server
      - ${BASE_CONFIG_DIR}/tdarr/configs:/app/configs
      - ${BASE_CONFIG_DIR}/tdarr/logs:/app/logs
      - ${BASE_MEDIA_DIR}/media:/media
      - ${BASE_MEDIA_DIR}/transcode/tdarr:/temp

    devices:
      - /dev/dri:/dev/dri
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: all
#            capabilities: [gpu]

#  tdarr-node:
#    container_name: tdarr-node
#    image: ghcr.io/haveagitgat/tdarr_node:latest
#    restart: unless-stopped
#    network_mode: service:tdarr
#    environment:
#      - TZ=Europe/London
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - UMASK_SET=002
#      - nodeName=MyExternalNode
#      - serverIP=0.0.0.0
#      - serverPort=8266
#      - inContainer=true
#      - ffmpegVersion=6
#      - NVIDIA_DRIVER_CAPABILITIES=all
#      - NVIDIA_VISIBLE_DEVICES=all
#
#    volumes:
#      - ${BASE_CONFIG_DIR}/tdarr/configs:/app/configs
#      - ${BASE_CONFIG_DIR}/tdarr/logs:/app/logs
#      - ${BASE_MEDIA_DIR}/media:/media
#      - ${BASE_MEDIA_DIR}/transcode/tdarr:/temp
#
#    devices:
#      - /dev/dri:/dev/dri
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: all
#            capabilities: [gpu]
