#!/bin/bash

usage="
$(basename "$0") [-hfts] -- Cat the logs of the media server stack. This stack includes...

Plex: The media server
Sadarr: Tool for tracking and finding downloads for TV shows
Ronarr: Tool for finding downloads for Movies
Sabnzbd: A binary newsreader to download what Sonarr/Radarr find
Transmission: A torrent download client
Jackett: A meta indexer for a wide range of torrent providers

Options:
    -h  Show this help text
    -f  Follow the log tail
    -t  Number of lines to tail (default 100)
    -s  Service to monitor
"

# Check both Docker and Docekr Compose are installed
if [ -z "$(docker --version)" ]; then
  printf "Docker is required to run this stack\n" >&2
  printf "Please see https://www.docker.com/\n" >&2
  exit 1
fi
if [ -z "$(docker-compose --version)" ]; then
  printf "Docker Compose is required to run this stack\n" >&2
  printf "Please see https://docs.docker.com/compose/overview/\n" >&2
  exit 1
fi

# Parse options
log_args=""
tail_count="100"
service=""
while getopts ':hfs:t:' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    f) log_args="$log_args -f"
       ;;
    t) tail_count="$OPTARG"
       ;;
    s) service="$OPTARG"
       ;;
    :) printf "missing argument for -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done

log_args="$log_args --tail $tail_count"
if [ ! -z "$service" ]; then
  log_args="$log_args $service"
fi

USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml logs $log_args
