#!/bin/bash

usage="
$(basename "$0") [-h] -- Stops the media server stack. This stack includes...

Plex: The media server
Sadarr: Tool for tracking and finding downloads for TV shows
Ronarr: Tool for finding downloads for Movies
Sabnzbd: A binary newsreader to download what Sonarr/Radarr find
Transmission: A torrent download client
Jackett: A meta indexer for a wide range of torrent providers

Options:
    -h  Show this help text
"

# Check both Docker and Docekr Compose are installed
if [ -z "$(docker --version)" ]; then
  printf "Docker is required to run this stack\n" >&2
  printf "Please see https://www.docker.com/\n" >&2
  exit 1
fi
if [ -z "$(docker-compose --version)" ]; then
  printf "Docker Compose is required to run this stack\n" >&2
  printf "Please see https://docs.docker.com/compose/overview/\n" >&2
  exit 1
fi

# Parse options
while getopts ':h' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done

USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml stop
